apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rollout.yaml
  - service.yaml
  - service-preview.yaml
  - virtualservice.yaml
  - configmap.yaml
  - analysis-template.yaml
  - promotion-template.yaml
  - promotion-rbac.yaml

namespace: default
